### ISSUE TITLE
[广州地铁] RMG中广州地铁风的一些问题与建议

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/rmp#114]
### **所有站点的问题。**
1.
![image](https://user-images.githubusercontent.com/108232422/207199247-7dd6e333-164f-42dd-9c1a-62696e31c89b.png)
**当线路号输入超过3个字符的时候，就会发现最后一个字符与中间分隔线重合。**
2.
![未标题-2](https://user-images.githubusercontent.com/108232422/207215451-dc0ae925-e42d-44ea-b513-8e76d8e5003e.png)
**某些情况下站点的英文于中文重叠。**
3.
![image](https://user-images.githubusercontent.com/108232422/207202399-4e736c0e-4e2d-4c3a-8135-c564d9a347d2.png)
**有时候一些站名不可避免的会很长，建议增加换行。**
_**这一点可以参考RMG的做法，使某些符号成为换行符。如下图：**_
![未标题-3](https://user-images.githubusercontent.com/108232422/207203631-cbce1533-0585-43a9-93b1-595d8b204bd0.png)
_**希望可以增加特殊符号换行功能。**_

### **换乘站**
![1666](https://user-images.githubusercontent.com/108232422/207200445-e1d1e4e0-f98d-4fe7-9097-44d70592aebf.png)
**换乘站点中会有线路穿过站点的情况。**

### **线路的问题**
![image](https://user-images.githubusercontent.com/108232422/207200931-cc419f88-be02-4369-907b-02e3e01a2738.png)
**下载地图的时候，经常会保留这些小点。我们后期还要一个像素一个像素的抠掉。希望可以改进一下，生成图片的时候隐藏这小东西。**

### **其它**
**希望增加广州地铁风格的铁路、城际、机场等元素，如图：**
![image](https://user-images.githubusercontent.com/108232422/207214799-5c008bd3-edaa-483e-aa2f-d0dbc36688b9.png)
![image](https://user-images.githubusercontent.com/108232422/207214883-8fb5b92d-a004-473a-bba5-159451be4bf2.png)
**希望可以采纳。**

**Comment by hackerfyl** [comment]
### **总结几点**
- [ ] 广州地铁站点线路序号偏移，与中线重合。
- [ ] 广州地铁站点站名中英文重叠。
- [ ] 广州地铁站点站名建议增加换行功能。
- [ ] 广州地铁换乘站线路穿过站点。
- [ ] 生成地图时建议隐藏线路节点。
- [ ] 建议增加广州地铁风格的小图标。

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议，现将一一回复您所提到的问题：

- [ ] 广州地铁站点线路序号偏移，与中线重合。 -> 广州地铁胶囊实现从rmg中拷贝而来，理应不会出现这种情况，我将进行进一步检查，见 #116 。
- [ ] 广州地铁站点站名中英文重叠。 -> 已确认，会在 #103 中一同修复，预期年底前上线。
- [ ] 广州地铁站点站名建议增加换行功能。 -> 已确认，会在 #103 中一同修复，预期年底前上线。
- [ ] 广州地铁换乘站线路穿过站点。 -> 已确认，见 #92 讨论，目前受限于开发者精力原因暂无法手绘精细站点图标，需要各位的帮助。
- [ ] 生成地图时建议隐藏线路节点。 -> 已修复，见 #115 。
- [ ] 建议增加广州地铁风格的小图标。 -> 目前已有rmg中风格机场车站乐园等元素，与广州地铁胶囊一样从rmg中拷贝而来，欢迎提交您绘制的广州地铁风格小图标(svg格式)并授权一切再利用的权力。

如有任何未经事宜，欢迎reopen此issue并发表新的comments。

**Comment by thekingofcity** [comment]
嗨，中英文重叠和换行相关的更新已经上线，您可以即可开始体验了！

**Comment by hackerfyl** [comment]
感谢开发者们关注我的建议！
